In [1]:
# Unit 2 Project
# Name: Meghan OConnell
# Date: 6/16/2023
# Due Date: 6/25/2023
# Course: CS379-2303A-01 Machine Learning

In [2]:
# Description:

# This is a supervised learning algorithm that uses a dataset
#    of patients with high blood pressue from Canada.

# This algorithm uses a Decision Tree method to predict whether a
#   patient has diabetes based on factors like age, sex and location

# I chose the Decision Tree method beocause it's simple and doesn't
#    required a lot of coding compared to other models 
#    (Introduction to Decision Trees: Why Should You Use Them? | 
#    365 Data Science, 2021)

In [3]:
# Importing libraries

# Pandas is how I'm reading and analyzing my data
import pandas as pd

# Numpy allows me to work with multidimensional arrays
import numpy as np

# Matplotlib is a big resource for plotting data
import matplotlib.pyplot as plt

# I will use seaborn also for plotting data
import seaborn as sns

# Importing scikit-learn?

In [4]:
#Reading the dataset
myData = pd.read_csv(r"C:\Users\letha\Local Documents\Jupyter\CS379\Unit2\BloodPressure.csv")

#Printing first 5 rows of data to confirm read was successful
myData.head(5)

REF_DATE     GEO  DGUID    Age_group    Sex       High_blood_pressure  \
0      1994  Canada    NaN  12-14 years  Males  With high blood pressure   
1      1994  Canada    NaN  12-14 years  Males  With high blood pressure   
2      1994  Canada    NaN  12-14 years  Males  With high blood pressure   
3      1994  Canada    NaN  12-14 years  Males  With high blood pressure   
4      1994  Canada    NaN  12-14 years  Males  With high blood pressure   

                                    Characteristics      UOM  UOM_ID  \
0                                 Number of persons  Persons     249   
1  Low 95% confidence interval -  number of persons  Persons     249   
2  High 95% confidence interval - number of persons  Persons     249   
3    Coefficient of variation for number of persons  Persons     249   
4                                           Percent  Percent     239   

  SCALAR_FACTOR  SCALAR_ID    VECTOR COORDINATE  VALUE STATUS  SYMBOL  \
0        units           0  v1889130  1.3.2.2.1    NaN      F     NaN   
1        units           0  v1889131  1.3.2.2.2    NaN      F     NaN   
2        units           0  v1889132  1.3.2.2.3    NaN      F     NaN   
3        units           0  v4009575  1.3.2.2.4    NaN      F     NaN   
4        units           0  v4009576  1.3.2.2.5    NaN      F     NaN   

   TERMINATED  DECIMALS  
0         NaN         0  
1         NaN         0  
2         NaN         0  
3         NaN         1  
4         NaN         1

In [5]:
# First I'm going to clean the data because there are many features
#    here I'm not going to use

In [6]:
#Getting an idea of the data size
myData.shape

(20592, 18)

In [7]:
#Counting columns with missing values
myData.isna().sum()

REF_DATE                   0
GEO                        0
DGUID                  20592
Age_group                  0
Sex                        0
High_blood_pressure        0
Characteristics            0
UOM                        0
UOM_ID                     0
SCALAR_FACTOR              0
SCALAR_ID                  0
VECTOR                     0
COORDINATE                 0
VALUE                  10592
STATUS                  7520
SYMBOL                 20592
TERMINATED             20592
DECIMALS                   0
dtype: int64

In [8]:
# Removing empty columns and columns that I just won't need
# None of my important columns have missing data
myData = myData.drop(['TERMINATED', 'SYMBOL', 'STATUS', 'VALUE', 
                      'COORDINATE', 'VECTOR', 'DGUID',
                      'UOM', 'Characteristics', 'DECIMALS',
                      'UOM_ID', 'SCALAR_FACTOR', 'SCALAR_ID'], 
                       axis=1)

In [9]:
# Viewing snapshot of data to confirm changes
myData.head(5)

REF_DATE     GEO    Age_group    Sex       High_blood_pressure
0      1994  Canada  12-14 years  Males  With high blood pressure
1      1994  Canada  12-14 years  Males  With high blood pressure
2      1994  Canada  12-14 years  Males  With high blood pressure
3      1994  Canada  12-14 years  Males  With high blood pressure
4      1994  Canada  12-14 years  Males  With high blood pressure

In [10]:
#Checking data types so I know what I need to change
myData.dtypes

REF_DATE                int64
GEO                    object
Age_group              object
Sex                    object
High_blood_pressure    object
dtype: object

In [11]:
# Checking what unique values exist
print('GEO: ' + myData['GEO'].unique())
print()
print('Age group: ' + myData['Age_group'].unique())
print()
print('Sex: ' + myData['Sex'].unique())
print()
print('High blood pressure: ' + myData['High_blood_pressure'].unique())


['GEO: Canada' 'GEO: Newfoundland and Labrador'
 'GEO: Prince Edward Island' 'GEO: Nova Scotia' 'GEO: New Brunswick'
 'GEO: Quebec' 'GEO: Ontario' 'GEO: Manitoba' 'GEO: Saskatchewan'
 'GEO: Alberta' 'GEO: British Columbia']

['Age group: 12-14 years' 'Age group: 12-19 years'
 'Age group: 15-19 years' 'Age group: 20-24 years'
 'Age group: 20-34 years' 'Age group: 25-34 years'
 'Age group: 35-44 years' 'Age group: 45-54 years'
 'Age group: 45-64 years' 'Age group: 55-64 years'
 'Age group: 65 years and over' 'Age group: 65-74 years'
 'Age group: 75 years and over']

['Sex: Males' 'Sex: Females']

['High blood pressure: With high blood pressure'
 'High blood pressure: Without high blood pressure'
 'High blood pressure: High blood pressure, not stated']


In [12]:
# Importing sklearn for the preprocessing properties
from sklearn.preprocessing import LabelEncoder
labelEncoder = LabelEncoder()

# Changing data types from 'GEO' and 'Sex'
myData.iloc[:, 1] = labelEncoder.fit_transform(myData.iloc[:, 1].values)
myData.iloc[:, 3] = labelEncoder.fit_transform(myData.iloc[:, 3].values)

# Checking my work
print(myData['GEO'].unique())
print(myData['Sex'].unique())


[ 2  5  8  6  4  9  7  3 10  0  1]
[1 0]


In [13]:
# Changing age group column
# I did it this way because I wanted the age groups to have
#    specific values for the minimum age of each group

ageGroup={'12-14 years':12, '12-19 years':12, '15-19 years':15, 
          '20-24 years':20, '20-34 years':20, '25-34 years':25,
          '35-44 years':35, '45-54 years':45, '45-64 years':45,
          '55-64 years':55, '65 years and over':65,
          '65-74 years':65, '75 years and over':75}
myData.Age_group = myData.Age_group.map(ageGroup)

# Checking my work
print(myData['Age_group'].unique())

[12 15 20 25 35 45 55 65 75]


In [14]:
# Changing high blood pressure column to an int data type
# I also wanted these to be mapped to specific values

bloodPressure1={'With high blood pressure':1,
 'Without high blood pressure':0,
 'High blood pressure, not stated':5}

myData.High_blood_pressure = myData.High_blood_pressure.map(bloodPressure1)

# Checking my work
print(myData['High_blood_pressure'].unique())

[1 0 5]


In [15]:
# Checking that all data types have been changed
myData.dtypes

REF_DATE               int64
GEO                    int32
Age_group              int64
Sex                    int32
High_blood_pressure    int64
dtype: object

In [16]:
# Checking size of the file after changes
myData.shape

(20592, 5)

In [17]:
# My decision tree is going to use the CART algorithm, as per
#    (Decision Tree Algorithm in Machine Learning - Javatpoint, 
#    2021)

In [18]:
# Extracting Independent and Dependent variables using 
#    an integer location pandas function
#    my y is the blood pressure column since that's what we're 
#    predicting

x = myData.iloc[:, 0:4]
y = myData.iloc[:, 4]

In [19]:
# I'm going to use 80% of my data to train the algorithm since 
#    this is a supervised algorithm.  20% will be for testing

from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x,y, test_size 
                    = 0.2, random_state = 0)

In [20]:
# Feature scaling to make sure my data is standardized
from sklearn.preprocessing import StandardScaler
st_x = StandardScaler()
x_train = st_x.fit_transform(x_train)
x_test = st_x.transform(x_test)

In [21]:
# Connecting the model to the training set
from sklearn.tree import DecisionTreeClassifier
classifier = DecisionTreeClassifier(criterion='entropy', random_state=0)
classifier.fit(x_train,y_train)

DecisionTreeClassifier(criterion='entropy', random_state=0)

In [22]:
# Predictng the test set result
y_pred = classifier.predict(x_test)

### References
Decision Tree Algorithm in Machine Learning - Javatpoint. (2021). Www.javatpoint.com. https://www.javatpoint.com/machine-learning-decision-tree-classification-algorithm

Elam, D. (2023, June 13). Unit 1 Live Chat: Introduction [chat]. Retrieved from Colorado Technical University, Virtual Campus, CS379-2303A-01: https://campus.ctuonline.edu

Elam, D. (2023, June 20). Unit 2 Live Chat: Machine Learning Algorithms [chat]. Retrieved from Colorado Technical University, Virtual Campus, CS379-2303A-01: https://campus.ctuonline.edu

Introduction to Decision Trees: Why Should You Use Them? | 365 Data Science. (2021, November 17). 365 Data Science. https://365datascience.com/tutorials/machine-learning-tutorials/decision-trees/

Tracyrenee. (2021, July 22). Using KMeans clustering to predict survivors of the Titanic. Medium; MLearning.ai. https://medium.com/mlearning-ai/using-kmeans-clustering-to-predict-survivors-of-the-titanic-ae3d3e959eb8

Randerson112358. (2019, July 22). Titanic Survival Prediction Using Machine Learning - Better Programming. Medium; Better Programming. https://betterprogramming.pub/titanic-survival-prediction-using-machine-learning-4c5ff1e3fa16